### ISSUE TITLE
Updating package.json creates trouble with Babel

### ISSUE THREAD

**Issue by bmoquist** [lang-ai/react-emails#1]
Thanks for making this project! Once I got the everything up and running, creating emails with React and sending in Node has worked great and been easy.

The repo's package.json is quite stale (pre-React 16!) so I bumped all the dependencies to latest and ran into trouble with Babel no longer transpiling the import statements. Node 8.1.4 would no longer run the transpiled example. 

To make the project work, I added ```babel-preset-node8``` to package.json and adjusted the build script. I didn't find a great solution to use the recommended babel-preset-env without ejecting CRA and using a .babelrc.

See below:

```js
{
  "name": "react-emails-example",
  "version": "1.0.0",
  "private": true,
  "main": "./server/createEmail.js",
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-eslint": "8.2.2",
    "babel-preset-node8": "^1.2.0",
    "babel-preset-react-app": "^3.1.1",
    "eslint": "4.19.1",
    "eslint-config-react-app": "2.1.0",
    "eslint-plugin-flowtype": "2.46.1",
    "eslint-plugin-import": "2.10.0",
    "eslint-plugin-jsx-a11y": "6.0.3",
    "eslint-plugin-react": "7.7.0",
    "node-fetch": "^2.1.2",
    "react-scripts": "1.1.4"
  },
  "dependencies": {
    "date-fns": "^1.28.3",
    "react": "^16.3.1",
    "react-dom": "^16.3.1"
  },
  "scripts": {
    "install": "NODE_ENV=production babel src --out-dir lib --presets=react-app",
    "build": "NODE_ENV=production babel src --out-dir lib --presets=react-app,node8",
    "start": "react-scripts start",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by albertorestifo** [comment]
Thanks for opening the issue!

In the end, I just added the CommonJS transform on top of the react preset.

It's not necessarey to eject form `create-react-app` to modify the babel configuration. The build for Node is made trough babel directly so it reads your `.babelrc`:

```
$ babel src --out-dir lib
```
